# Generated by Django 5.2 on 2025-04-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
